// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBylDdBXP6U5Ba6MqX8dUrZ4Q-N9nR-164',
    appId: '1:539525530321:android:80fdb2100f11d2c57abbf0',
    messagingSenderId: '539525530321',
    projectId: 'healthkit-flutter',
    storageBucket: 'healthkit-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZeBJLxmXN-4MeUmNis9AftsI0rVm8YS0',
    appId: '1:539525530321:ios:8a59ad45c9858f327abbf0',
    messagingSenderId: '539525530321',
    projectId: 'healthkit-flutter',
    storageBucket: 'healthkit-flutter.firebasestorage.app',
    androidClientId: '539525530321-b3gh8h68om4db88dqa69g4i3ki0u6nhq.apps.googleusercontent.com',
    iosClientId: '539525530321-rr38uki81p5qthg1n6ei3roiei65hnsu.apps.googleusercontent.com',
    iosBundleId: 'com.hypeteq.fitnessapp',
  );

}