platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks! :linkage => :static

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  load File.join(__dir__, 'podhelper.rb') # Tải file podhelper.rb từ thư mục hiện tại
end

target 'Runner' do
  flutter_installation

  # Allow non-modular includes in framework modules
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  # Add any additional Flutter dependencies here
  flutter_install_all_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Allow non-modular includes in framework modules
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
