# This file is generated by Flutter. It is used to integrate Flutter with CocoaPods.

def flutter_application_path
  File.expand_path('..', __FILE__)
end

def flutter_additional_ios_build_settings(target)
  target.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
end

# Load the Flutter environment
flutter_application_path = flutter_application_path
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'flutter_export_environment.sh')))
